### ISSUE TITLE
Does not can log in into haiku depot web

### ISSUE THREAD

**Issue by lelldorin** [aplgithub/haikudepotserver#134]
Can anyone check if i am on a backlist please?

**Comment by diversys** [comment]
What is the error message you're seeing?

**Comment by aplgithub** [comment]
@lelldorin -- Perhaps you could [contact me](mailto:apl@lindesay.co.nz) out-of-band regarding this so that any authentication details are not discussed in a public ticket.  As a control, can you please check the behavior on a mainstream browser (Chrome or Firefox) on a mainstream platform such as macOS, Linux or Windows.

**Comment by aplgithub** [comment]
@lelldorin -- Are you still able to see this problem?  If not, can I close this ticket?

**Comment by aplgithub** [comment]
No further details provided - will close.
