### ISSUE TITLE
haikuports repo is outdated

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#135]
For example http://cgit.haiku-os.org/haiku/commit/?h=hrev51290 added FilWip to x86_64 repo but I can't find it in the web depot.

**Comment by aplgithub** [comment]
The [hpkr](http://packages.haiku-os.org/haikuports/master/repo/x86_64/current/repo) file contains the package;

```
filwip : 1.0.0..8 : X86_64
filwip_source : 1.0.0..8 : SOURCE
```

However it is not possible to find this on the HDS web interface.  I can't see a problem from the logs so using the [REST](https://depot.haiku-os.org/__docs/ch13.html#api-importrepositorydata) API for importing a repositories' data I can [trigger](https://depot.haiku-os.org/__repository/haikuports/import) an import run.  This is easy with curl;

```
curl "https://depot.haiku-os.org/__repository/haikuports/import"
```

Looks like there is a problem with the repository server's DNS resolution;

```
2017-07-19 09:13:21,418 / [job-run-3...] ERROR o.h.h.r.j.RepositoryHpkrIngressJobRunner - a problem has arisen processing a repository file for repository haikuports
java.lang.RuntimeException: a problem has arisen processing a repository file for repository source RepositorySource[code=haikuports_x86] from url 'http://packages.haiku-os.org/haikuports/master/repo/x86/current/repo'
...
Caused by: java.net.UnknownHostException: packages.haiku-os.org
...
```

Looks like it is caused by [this](https://stackoverflow.com/questions/1608503/domain-name-resolution-not-working-in-java-applications-on-ubuntu64-9-04-machine).  I made a spot-change to the launch script and it seems to be importing again now.

I'll take the 'hot patch' out tonight and then re-deploy properly from RPM with the changed launch script.

Thanks for notifying of this issue.

**Comment by aplgithub** [comment]
Now deployed properly via RPM with this change.
