### ISSUE TITLE
Switch to new HaikuPorts repos

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#139]
Currently Featured packages in HD doesn't list anything, probably due to the switch to new repos:

https://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_gcc2/current
https://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_64/current

**Comment by aplgithub** [comment]
Changed the repositories' URLs and had to re-deploy an update to handle "gopher://" URLs.

**Comment by diversys** [comment]
Hmm, Featured packages view is still empty here...

**Comment by aplgithub** [comment]
Oh I see; you are talking about the *desktop* application rather than the *web* application.

I also realise that changing the URL for those will cause problems for existing users so I have changed it back again for the time being.

I will take this discussion over to the mailing list because it will require discussion about how to handle it.

**Comment by aplgithub** [comment]
Something you can do to see what is going on, is to launch HaikuDepot from a terminal.  The logging into the stdout should show you what is going on.
