### ISSUE TITLE
Downloading hpkgs from HDS broken

### ISSUE THREAD

**Issue by humdingerb** [aplgithub/haikudepotserver#156]
If you click a `Download package 'hpkg' file` link of a package (e.g. [ArmyKnife](https://depot.haiku-os.org/#!/pkg/armyknife/haikuports/5/1/0/-/4/x86_gcc2), it tries the URL:
`http://buildmaster/haikuports/repository/master/x86_gcc2/current/packages/armyknife-5.1.0-4-x86_gcc2.hpkg`

Which fails, Web+ says "Server not found".

**Comment by aplgithub** [comment]
Hi Humdinger; This is because Alex has configured the world-visible URL for the repository to an internal internet address.  I have asked him to reconfigure the repositories correctly, but he hasn't resolved this yet.  Can you please take this to the mailing list (dev-ops / admin or HDS) because it is an operational issue rather than a software issue or a bug.
