### ISSUE TITLE
HDS logs out on page reload

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#2]
Logging in and reloading a page logs me out. Tested with Firefox and Chrome.

**Comment by waddlesplash** [comment]
Opening a page in a new tab doesn't work either. Maybe the session isn't being stored in cookies.

**Comment by aplgithub** [comment]
Hi; You are correct in that there are no sessions or cookies.  The application is stateless.  See [here](http://www.silvereye.co.nz/tmp/haikudepotserver-docs-5jan2015-tmp.pdf) under "5.1 Authentication".

**Comment by aplgithub** [comment]
The currently logged in user's token is now stored in the browser's local storage rather than in the "state of the page".  This means that opening a new tab will retain your authentication.  This is quite a complex change; please mail through or raise an issue on GitHub if you see any anomalies with it. In case you are wondering; the system does not use cookies in order to keep the back-end system entirely stateless.  This should allow it to scale up later on with less complexity.
