### ISSUE TITLE
Package summaries are not shown for Haiku repo on the search page

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#77]
Package summaries are missing for packages in Haiku repo, except for WebPositive.
https://depot.haiku-os.org/#/?srchexpr=haiku_

**Comment by aplgithub** [comment]
Sorry, I don't really understand this ticket.  Would you please elaborate carefully explaining what steps you took together with what you expected to see and what you actually saw?

**Comment by diversys** [comment]
When one search for package name (e.g. bepdf) the resulting search page includes package name "BePDF" as well as its summary "The PDF viewer for Haiku.". This doesn't happen with packages from haiku repo, summary is missing for them.

**Comment by aplgithub** [comment]
Hi @diversys; try this and let me know if it helps explain better how it works and let me know if there is still an issue...

* Opt to show "HaikuPorts" and "Haiku" repositories
* Search for "viewer" then you will see the "BePDF" package with the summary shown below the title in grey and the search keyword "viewer" in the summary highlighted.  This is because the word "viewer" is in the summary and not in the title.
* Search for "pdf" then you will get "BePDF" without the summary shown because the word "pdf" is in the name/title of the package.  It is also present in the summary, but since the title is already hit, the summary is not shown.
* Search for "base" and you will get the "Haiku" package shown with the search keyword "base" highlighted in the summary which is shown below the package title.

**Comment by diversys** [comment]
I wasn't aware of that if the title is already hit, the summary is not shown. If it works as intended feel free to close it.

**Comment by stippi** [comment]
I think always showing the summary would make it easier for the user to decide whether a search result is relevant, no?

**Comment by diversys** [comment]
Indeed.

**Comment by aplgithub** [comment]
ok - will show them anyway.

**Comment by diversys** [comment]
On a related note, how about showing the summary on the home page as well? There seem to be enough room for 15 packages to have both package name and summary at the same time without having scrollbars.

**Comment by stippi** [comment]
+1. There is a lot of empty space in the list for me as well, which I would like to see used for the summary.

**Comment by aplgithub** [comment]
Hi @stippi & @diversys; that change is in place for the next version now.

**Comment by diversys** [comment]
Hmm, if you search for "qt" the following packages don't have summaries:
libdbusmenu_qt_x86
libdbusmenu_qt_x86_devel
