### ISSUE TITLE
Unable to login under Haiku

### ISSUE THREAD

**Issue by diversys** [aplgithub/haikudepotserver#80]
Upon entering login/password I get
Oh darn! Something has gone wrong with your use of this web application.

Tried Web+, QupZilla 1.7.0 and 1.8.6 - same error everywhere.

Asked humdinger to give it a try and he is able to login no problem.

**Comment by aplgithub** [comment]
That's strange.  I have had a look at the application-server log and I can't see any obvious problem reported there.  As a test, can you please Firefox or Chrome on another platform and can you also get me the java-script log from the browser in case there are any errors that are appearing there?

**Comment by diversys** [comment]
Firefox and Chrome works just fine here. Can't find java-script log in QupZilla.

**Comment by aplgithub** [comment]
The actual page error in Web+ (Window > Script Console) is...

```
unhandled error; Error: at attempt has been made to set a token that has expired already
```

It turns out that the following JS code...

```
new Date().getTime()
```

...appears to be returning millis since 1970-01-01 00:00:00 in the *local* time zone rather than UTC.  Likewise on Haiku it seems that the bash command...

```
date +%s000
```
...gives the offset also relative to the *local* time zone rather than UTC.

I think that in general these millisecond offsets need to be relative to UTC rather than the local time-zone.  This causes a problem for the page logic because the token providing authentication from the application server has an expiry on it that expiry is represented as a millisecond offset since 1970-01-01 00:00:00 UTC and so when it compares with the current time on the browser where it is running, in the case of Web+ it appears to have already expired.

**Comment by diversys** [comment]
Ok, figured out what happened. I have Haiku running in VirtualBox and I use "Save the machine state" rather then shutting down Haiku when needed. Upon restore VBoxTray doesn't sync guest system time with the host which causes Haiku to be stuck back in time. 

After using Synchronize button in Time preflet I was able to login using Web+ as well as QupZilla. However, it would've beeen nice if HDS wasn't that strict :)

**Comment by aplgithub** [comment]
Ah yes and if I set the VirtualBox VM to supply the guest with UTC time, set Haiku as receiving UTC time and set my Time Zone then it works!  Maybe setting the time-zone ought to be part of the Haiku installation procedure.  I'll put a few words about this in the documentation.
